// Generated by scripts/generate-config-schema.mjs from data/config-schema.json.
// Do not edit. Edit the schema and re-run the generator; `pixi run check-config-schema`
// fails the build when this file is stale.
//
// The ranges data/config-schema.json declares, which config_schema_tests.cpp holds to the
// constants the flat readers guard with. Nothing outside cpp/tests includes it.

#pragma once

#include <cstddef>

namespace concept_ranges {

struct ConceptRange {
    const char* id;
    bool has_min;
    double min;
    bool has_max;
    double max;
};

inline constexpr ConceptRange kConceptRanges[] = {
    { "UdpPort", true, 1, true, 65535 },
    { "LocalSmoothing", true, 0, true, 1 },
    { "RemoteSmoothing", true, 0, true, 1 },
    { "DataFreshnessMs", true, 1, true, 2147483647 },
    { "PositionLimitX", true, 0, true, 10 },
    { "PositionLimitY", true, 0, true, 10 },
    { "PositionLimitYDown", true, 0, true, 10 },
    { "PositionLimitZ", true, 0, true, 10 },
    { "PositionLimitZBack", true, 0, true, 10 },
    { "CollisionMargin", true, 0, false, 0 },
    { "CollisionReleaseSmoothing", true, 0, true, 1 },
    { "TrackerPivotForward", true, 0, true, 10 },
    { "TrackerPivotUp", true, 0, true, 10 },
    { "LightMultiplier", true, 0, true, 5 },
};

inline constexpr size_t kConceptRangeCount = sizeof(kConceptRanges) / sizeof(kConceptRanges[0]);

}  // namespace concept_ranges
