// Generated by scripts/generate-config-schema.mjs from data/pipeline-conformance.json.
// Do not edit. Edit preference_modes and re-run the generator; `pixi run check-config-schema`
// fails the build when this file is stale.
//
// The EXPECTATION tracking_mode_tests.cpp holds cameraunlock/tracking/tracking_mode.h to.
// Nothing outside cpp/tests includes it: the runtime mapping is hand-written, so an edit
// to either side alone fails the test.

#pragma once

#include <cameraunlock/tracking/tracking_mode.h>

#include <cstddef>

namespace preference_modes {

struct TrackingModeExpectation {
    const char* name;
    cameraunlock::TrackingMode mode;
    bool rotation_enabled;
    bool position_enabled;
};

// preference_modes.tracking_mode.modes in file order, which is the cycle order.
inline constexpr TrackingModeExpectation kTrackingModes[] = {
    { "both", cameraunlock::TrackingMode::RotationAndPosition, true, true },
    { "rotation", cameraunlock::TrackingMode::RotationOnly, true, false },
    { "position", cameraunlock::TrackingMode::PositionOnly, false, true },
};

inline constexpr size_t kTrackingModeCount = sizeof(kTrackingModes) / sizeof(kTrackingModes[0]);

}  // namespace preference_modes
