// Generated by scripts/generate-config-schema.mjs from data/config-schema.json.
// Do not edit. Edit the schema and re-run the generator; `pixi run check-config-schema`
// fails the build when this file is stale.

#pragma once

#include <cstddef>
#include <limits>

namespace cameraunlock::config::schema {

/// The concepts a canonical config file writes: every concept data/config-schema.json marks
/// canonical, in its concepts order, which is the order a section's concept rows are written in.
enum class Concept {
    UdpPort,
    EnableOnStartup,
    LocalSmoothing,
    RemoteSmoothing,
    WorldSpaceYaw,
    AimDecoupling,
    RotationEnabled,
    DataFreshnessMs,
    PositionEnabled,
    PositionAllowed,
    TrueFreeLook,
    PositionLimitX,
    PositionLimitY,
    PositionLimitYDown,
    PositionLimitZ,
    PositionLimitZBack,
    CollisionEnabled,
    CollisionMargin,
    CollisionChannel,
    CollisionReleaseSmoothing,
    TrackerPivotForward,
    TrackerPivotUp,
    ToggleKey,
    CycleTrackingModeKey,
    YawModeKey,
    TrueFreeLookKey,
    LightFollowsHead,
    LightMultiplier,
};

/// What a concept's field holds, which fixes its codec: kBool is BoolCodec over bool, kInteger
/// IntCodec over an integral type that holds the concept's range, kFloating FloatCodec or
/// DoubleCodec, and kHotkey HotkeyCodec over std::string.
enum class ValueFamily { kBool, kInteger, kFloating, kHotkey };

/// The schema's facts about one canonical concept. kMin and kMax, both inclusive, exist for the
/// kInteger family (within int) and the kFloating family (as float); a bound the schema leaves
/// open is the limit of the schema type. kCanonicalDefault is the value a canonical file starts
/// with where it differs from the flat readers' default (a hotkey concept's binding list,
/// CollisionEnabled's true), else nullptr. kDefaultText is the schema's default as text the
/// concept's codec reads: the canonical_default where there is one, else the schema's value as it
/// is written there. kGlobal is false for a concept that holds engine data (the engine's own
/// units, a channel number): every game keeps its own value, Defaults.ini never carries it, and a
/// config table writes its row as an Engine row.
template <Concept Id>
struct ConceptTraits;

template <>
struct ConceptTraits<Concept::UdpPort> {
    static constexpr const char* kSection = "Network";
    static constexpr const char* kKey = "UdpPort";
    static constexpr ValueFamily kFamily = ValueFamily::kInteger;
    static constexpr long long kMin = 1;
    static constexpr long long kMax = 65535;
    static constexpr const char* kFileComment[] = {"UDP port the mod receives tracker data on (OpenTrack protocol)."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "4242";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::EnableOnStartup> {
    static constexpr const char* kSection = "General";
    static constexpr const char* kKey = "EnableOnStartup";
    static constexpr ValueFamily kFamily = ValueFamily::kBool;
    static constexpr const char* kFileComment[] = {"true: head tracking is on when the game starts. ToggleKey turns it on and off."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "true";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::LocalSmoothing> {
    static constexpr const char* kSection = "Smoothing";
    static constexpr const char* kKey = "LocalSmoothing";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 1.0f;
    static constexpr const char* kFileComment[] = {"Smoothing when the tracker runs on this PC. 0 is the least, 1 the most."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::RemoteSmoothing> {
    static constexpr const char* kSection = "Smoothing";
    static constexpr const char* kKey = "RemoteSmoothing";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 1.0f;
    static constexpr const char* kFileComment[] = {"Smoothing when the tracker is another device on the network, such as a phone.", "0 is the least, 1 the most."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0.15";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::WorldSpaceYaw> {
    static constexpr const char* kSection = "General";
    static constexpr const char* kKey = "WorldSpaceYaw";
    static constexpr ValueFamily kFamily = ValueFamily::kBool;
    static constexpr const char* kFileComment[] = {"true: yaw turns around the world's up axis. false: around the camera's own up axis."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "true";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::AimDecoupling> {
    static constexpr const char* kSection = "General";
    static constexpr const char* kKey = "AimDecoupling";
    static constexpr ValueFamily kFamily = ValueFamily::kBool;
    static constexpr const char* kFileComment[] = {"true: your aim stays with the mouse or controller while your head moves the view."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "true";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::RotationEnabled> {
    static constexpr const char* kSection = "General";
    static constexpr const char* kKey = "RotationEnabled";
    static constexpr ValueFamily kFamily = ValueFamily::kBool;
    static constexpr const char* kFileComment[] = {"true: turning your head turns the view.", "Tracking mode at startup, with PositionEnabled. The mode hotkey changes both."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "true";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::DataFreshnessMs> {
    static constexpr const char* kSection = "General";
    static constexpr const char* kKey = "DataFreshnessMs";
    static constexpr ValueFamily kFamily = ValueFamily::kInteger;
    static constexpr long long kMin = 1;
    static constexpr long long kMax = 2147483647;
    static constexpr const char* kFileComment[] = {"Milliseconds a tracker packet stays current. Once the tracker has sent nothing", "for this long, the mod stops following it until data arrives again."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "500";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::PositionEnabled> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "PositionEnabled";
    static constexpr ValueFamily kFamily = ValueFamily::kBool;
    static constexpr const char* kFileComment[] = {"true: moving your head moves the view.", "Tracking mode at startup, with RotationEnabled. The mode hotkey changes both."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "true";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::PositionAllowed> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "PositionAllowed";
    static constexpr ValueFamily kFamily = ValueFamily::kBool;
    static constexpr const char* kFileComment[] = {"false: head tracking runs rotation only, whatever RotationEnabled and PositionEnabled say,", "and the mode hotkey skips the modes that use position."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "true";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::TrueFreeLook> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "TrueFreeLook";
    static constexpr ValueFamily kFamily = ValueFamily::kBool;
    static constexpr const char* kFileComment[] = {"false: while you aim down the sights, leaning keeps your eye on the sights.", "true: the weapon stays put and your head moves freely around it (true free look)."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "false";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::PositionLimitX> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "PositionLimitX";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 10.0f;
    static constexpr const char* kFileComment[] = {"How far, in metres, leaning left or right can move the view."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0.3";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::PositionLimitY> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "PositionLimitY";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 10.0f;
    static constexpr const char* kFileComment[] = {"How far, in metres, raising your head can move the view."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0.2";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::PositionLimitYDown> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "PositionLimitYDown";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 10.0f;
    static constexpr const char* kFileComment[] = {"How far, in metres, lowering your head can move the view."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0.2";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::PositionLimitZ> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "PositionLimitZ";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 10.0f;
    static constexpr const char* kFileComment[] = {"How far, in metres, leaning forward can move the view."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0.4";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::PositionLimitZBack> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "PositionLimitZBack";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 10.0f;
    static constexpr const char* kFileComment[] = {"How far, in metres, leaning back can move the view."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0.1";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::CollisionEnabled> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "CollisionEnabled";
    static constexpr ValueFamily kFamily = ValueFamily::kBool;
    static constexpr const char* kFileComment[] = {"true: leaning stops at walls instead of moving the view through them."};
    static constexpr const char* kCanonicalDefault = "true";
    static constexpr const char* kDefaultText = "true";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::CollisionMargin> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "CollisionMargin";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = std::numeric_limits<float>::max();
    static constexpr const char* kFileComment[] = {"How far the view is held off a wall when you lean into it, in the game's own units."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0.1";
    static constexpr bool kGlobal = false;
};

template <>
struct ConceptTraits<Concept::CollisionChannel> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "CollisionChannel";
    static constexpr ValueFamily kFamily = ValueFamily::kInteger;
    static constexpr long long kMin = -2147483647 - 1;
    static constexpr long long kMax = 2147483647;
    static constexpr const char* kFileComment[] = {"Which of the game's collision channels the wall check tests against."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0";
    static constexpr bool kGlobal = false;
};

template <>
struct ConceptTraits<Concept::CollisionReleaseSmoothing> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "CollisionReleaseSmoothing";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 1.0f;
    static constexpr const char* kFileComment[] = {"How gently the view eases back out after a wall stopped a lean.", "0 is the quickest, 1 the slowest."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0.9";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::TrackerPivotForward> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "TrackerPivotForward";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 10.0f;
    static constexpr const char* kFileComment[] = {"Metres from the pivot of your neck forward to the point the tracker follows.", "Used to remove the lean that turning your head adds. 0 here and in TrackerPivotUp turns it off."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::TrackerPivotUp> {
    static constexpr const char* kSection = "Position";
    static constexpr const char* kKey = "TrackerPivotUp";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 10.0f;
    static constexpr const char* kFileComment[] = {"Metres from the pivot of your neck up to the point the tracker follows."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "0";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::ToggleKey> {
    static constexpr const char* kSection = "Hotkeys";
    static constexpr const char* kKey = "ToggleKey";
    static constexpr ValueFamily kFamily = ValueFamily::kHotkey;
    static constexpr const char* kFileComment[] = {"Turns head tracking on and off."};
    static constexpr const char* kCanonicalDefault = "End, Ctrl+Shift+Y";
    static constexpr const char* kDefaultText = "End, Ctrl+Shift+Y";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::CycleTrackingModeKey> {
    static constexpr const char* kSection = "Hotkeys";
    static constexpr const char* kKey = "CycleTrackingModeKey";
    static constexpr ValueFamily kFamily = ValueFamily::kHotkey;
    static constexpr const char* kFileComment[] = {"Changes the tracking mode: rotation and position, rotation only, position only."};
    static constexpr const char* kCanonicalDefault = "PageUp, Ctrl+Shift+G";
    static constexpr const char* kDefaultText = "PageUp, Ctrl+Shift+G";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::YawModeKey> {
    static constexpr const char* kSection = "Hotkeys";
    static constexpr const char* kKey = "YawModeKey";
    static constexpr ValueFamily kFamily = ValueFamily::kHotkey;
    static constexpr const char* kFileComment[] = {"Switches yaw between the world's up axis and the camera's own (WorldSpaceYaw)."};
    static constexpr const char* kCanonicalDefault = "PageDown, Ctrl+Shift+H";
    static constexpr const char* kDefaultText = "PageDown, Ctrl+Shift+H";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::TrueFreeLookKey> {
    static constexpr const char* kSection = "Hotkeys";
    static constexpr const char* kKey = "TrueFreeLookKey";
    static constexpr ValueFamily kFamily = ValueFamily::kHotkey;
    static constexpr const char* kFileComment[] = {"Switches between keeping your eye on the sights and true free look (TrueFreeLook)."};
    static constexpr const char* kCanonicalDefault = "Insert, Ctrl+Shift+U";
    static constexpr const char* kDefaultText = "Insert, Ctrl+Shift+U";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::LightFollowsHead> {
    static constexpr const char* kSection = "Light";
    static constexpr const char* kKey = "LightFollowsHead";
    static constexpr ValueFamily kFamily = ValueFamily::kBool;
    static constexpr const char* kFileComment[] = {"true: a light you carry points where you look instead of where you aim."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "true";
    static constexpr bool kGlobal = true;
};

template <>
struct ConceptTraits<Concept::LightMultiplier> {
    static constexpr const char* kSection = "Light";
    static constexpr const char* kKey = "LightMultiplier";
    static constexpr ValueFamily kFamily = ValueFamily::kFloating;
    static constexpr float kMin = 0.0f;
    static constexpr float kMax = 5.0f;
    static constexpr const char* kFileComment[] = {"How far the light turns for each degree your head turns.", "1 matches the view, 0 keeps the light on your aim."};
    static constexpr const char* kCanonicalDefault = nullptr;
    static constexpr const char* kDefaultText = "1.5";
    static constexpr bool kGlobal = true;
};

/// One canonical concept, for code that walks them all. kConcepts[static_cast<std::size_t>(id)]
/// describes id. `file_comment` holds `file_comment_lines` lines; the rest are nullptr.
/// `default_text` is ConceptTraits<id>::kDefaultText, and `global` ConceptTraits<id>::kGlobal.
struct ConceptInfo {
    Concept id;
    const char* name;
    const char* section;
    const char* key;
    ValueFamily family;
    const char* file_comment[2];
    std::size_t file_comment_lines;
    const char* canonical_default;
    const char* default_text;
    bool global;
};

inline constexpr ConceptInfo kConcepts[] = {
    {Concept::UdpPort, "UdpPort", "Network", "UdpPort", ValueFamily::kInteger, {"UDP port the mod receives tracker data on (OpenTrack protocol).", nullptr}, 1, nullptr, "4242", true},
    {Concept::EnableOnStartup, "EnableOnStartup", "General", "EnableOnStartup", ValueFamily::kBool, {"true: head tracking is on when the game starts. ToggleKey turns it on and off.", nullptr}, 1, nullptr, "true", true},
    {Concept::LocalSmoothing, "LocalSmoothing", "Smoothing", "LocalSmoothing", ValueFamily::kFloating, {"Smoothing when the tracker runs on this PC. 0 is the least, 1 the most.", nullptr}, 1, nullptr, "0", true},
    {Concept::RemoteSmoothing, "RemoteSmoothing", "Smoothing", "RemoteSmoothing", ValueFamily::kFloating, {"Smoothing when the tracker is another device on the network, such as a phone.", "0 is the least, 1 the most."}, 2, nullptr, "0.15", true},
    {Concept::WorldSpaceYaw, "WorldSpaceYaw", "General", "WorldSpaceYaw", ValueFamily::kBool, {"true: yaw turns around the world's up axis. false: around the camera's own up axis.", nullptr}, 1, nullptr, "true", true},
    {Concept::AimDecoupling, "AimDecoupling", "General", "AimDecoupling", ValueFamily::kBool, {"true: your aim stays with the mouse or controller while your head moves the view.", nullptr}, 1, nullptr, "true", true},
    {Concept::RotationEnabled, "RotationEnabled", "General", "RotationEnabled", ValueFamily::kBool, {"true: turning your head turns the view.", "Tracking mode at startup, with PositionEnabled. The mode hotkey changes both."}, 2, nullptr, "true", true},
    {Concept::DataFreshnessMs, "DataFreshnessMs", "General", "DataFreshnessMs", ValueFamily::kInteger, {"Milliseconds a tracker packet stays current. Once the tracker has sent nothing", "for this long, the mod stops following it until data arrives again."}, 2, nullptr, "500", true},
    {Concept::PositionEnabled, "PositionEnabled", "Position", "PositionEnabled", ValueFamily::kBool, {"true: moving your head moves the view.", "Tracking mode at startup, with RotationEnabled. The mode hotkey changes both."}, 2, nullptr, "true", true},
    {Concept::PositionAllowed, "PositionAllowed", "Position", "PositionAllowed", ValueFamily::kBool, {"false: head tracking runs rotation only, whatever RotationEnabled and PositionEnabled say,", "and the mode hotkey skips the modes that use position."}, 2, nullptr, "true", true},
    {Concept::TrueFreeLook, "TrueFreeLook", "Position", "TrueFreeLook", ValueFamily::kBool, {"false: while you aim down the sights, leaning keeps your eye on the sights.", "true: the weapon stays put and your head moves freely around it (true free look)."}, 2, nullptr, "false", true},
    {Concept::PositionLimitX, "PositionLimitX", "Position", "PositionLimitX", ValueFamily::kFloating, {"How far, in metres, leaning left or right can move the view.", nullptr}, 1, nullptr, "0.3", true},
    {Concept::PositionLimitY, "PositionLimitY", "Position", "PositionLimitY", ValueFamily::kFloating, {"How far, in metres, raising your head can move the view.", nullptr}, 1, nullptr, "0.2", true},
    {Concept::PositionLimitYDown, "PositionLimitYDown", "Position", "PositionLimitYDown", ValueFamily::kFloating, {"How far, in metres, lowering your head can move the view.", nullptr}, 1, nullptr, "0.2", true},
    {Concept::PositionLimitZ, "PositionLimitZ", "Position", "PositionLimitZ", ValueFamily::kFloating, {"How far, in metres, leaning forward can move the view.", nullptr}, 1, nullptr, "0.4", true},
    {Concept::PositionLimitZBack, "PositionLimitZBack", "Position", "PositionLimitZBack", ValueFamily::kFloating, {"How far, in metres, leaning back can move the view.", nullptr}, 1, nullptr, "0.1", true},
    {Concept::CollisionEnabled, "CollisionEnabled", "Position", "CollisionEnabled", ValueFamily::kBool, {"true: leaning stops at walls instead of moving the view through them.", nullptr}, 1, "true", "true", true},
    {Concept::CollisionMargin, "CollisionMargin", "Position", "CollisionMargin", ValueFamily::kFloating, {"How far the view is held off a wall when you lean into it, in the game's own units.", nullptr}, 1, nullptr, "0.1", false},
    {Concept::CollisionChannel, "CollisionChannel", "Position", "CollisionChannel", ValueFamily::kInteger, {"Which of the game's collision channels the wall check tests against.", nullptr}, 1, nullptr, "0", false},
    {Concept::CollisionReleaseSmoothing, "CollisionReleaseSmoothing", "Position", "CollisionReleaseSmoothing", ValueFamily::kFloating, {"How gently the view eases back out after a wall stopped a lean.", "0 is the quickest, 1 the slowest."}, 2, nullptr, "0.9", true},
    {Concept::TrackerPivotForward, "TrackerPivotForward", "Position", "TrackerPivotForward", ValueFamily::kFloating, {"Metres from the pivot of your neck forward to the point the tracker follows.", "Used to remove the lean that turning your head adds. 0 here and in TrackerPivotUp turns it off."}, 2, nullptr, "0", true},
    {Concept::TrackerPivotUp, "TrackerPivotUp", "Position", "TrackerPivotUp", ValueFamily::kFloating, {"Metres from the pivot of your neck up to the point the tracker follows.", nullptr}, 1, nullptr, "0", true},
    {Concept::ToggleKey, "ToggleKey", "Hotkeys", "ToggleKey", ValueFamily::kHotkey, {"Turns head tracking on and off.", nullptr}, 1, "End, Ctrl+Shift+Y", "End, Ctrl+Shift+Y", true},
    {Concept::CycleTrackingModeKey, "CycleTrackingModeKey", "Hotkeys", "CycleTrackingModeKey", ValueFamily::kHotkey, {"Changes the tracking mode: rotation and position, rotation only, position only.", nullptr}, 1, "PageUp, Ctrl+Shift+G", "PageUp, Ctrl+Shift+G", true},
    {Concept::YawModeKey, "YawModeKey", "Hotkeys", "YawModeKey", ValueFamily::kHotkey, {"Switches yaw between the world's up axis and the camera's own (WorldSpaceYaw).", nullptr}, 1, "PageDown, Ctrl+Shift+H", "PageDown, Ctrl+Shift+H", true},
    {Concept::TrueFreeLookKey, "TrueFreeLookKey", "Hotkeys", "TrueFreeLookKey", ValueFamily::kHotkey, {"Switches between keeping your eye on the sights and true free look (TrueFreeLook).", nullptr}, 1, "Insert, Ctrl+Shift+U", "Insert, Ctrl+Shift+U", true},
    {Concept::LightFollowsHead, "LightFollowsHead", "Light", "LightFollowsHead", ValueFamily::kBool, {"true: a light you carry points where you look instead of where you aim.", nullptr}, 1, nullptr, "true", true},
    {Concept::LightMultiplier, "LightMultiplier", "Light", "LightMultiplier", ValueFamily::kFloating, {"How far the light turns for each degree your head turns.", "1 matches the view, 0 keeps the light on your aim."}, 2, nullptr, "1.5", true},
};

inline constexpr std::size_t kConceptCount = sizeof(kConcepts) / sizeof(kConcepts[0]);

/// The schema's sections, in the order a canonical file writes them.
inline constexpr const char* kSections[] = {
    "Network",
    "General",
    "Sensitivity",
    "Inversion",
    "Smoothing",
    "Position",
    "Hotkeys",
    "Reticle",
    "Light",
};

inline constexpr std::size_t kSectionCount = sizeof(kSections) / sizeof(kSections[0]);

/// A concept the canonical format does not write. `normalized` is what ResolveConfigKey returns
/// for its key and every alias; `reason` is the line a player is shown for such a key.
struct NonCanonicalConcept {
    const char* name;
    const char* section;
    const char* key;
    const char* normalized;
    const char* reason;
};

inline constexpr NonCanonicalConcept kNonCanonicalConcepts[] = {
    {"YawSensitivity", "Sensitivity", "YawSensitivity", "yawsensitivity", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"PitchSensitivity", "Sensitivity", "PitchSensitivity", "pitchsensitivity", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"RollSensitivity", "Sensitivity", "RollSensitivity", "rollsensitivity", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"InvertYaw", "Inversion", "InvertYaw", "invertyaw", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"InvertPitch", "Inversion", "InvertPitch", "invertpitch", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"InvertRoll", "Inversion", "InvertRoll", "invertroll", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"ShowReticle", "Reticle", "ShowReticle", "showreticle", "Whether a reticle is shown is not a setting."},
    {"ReticleColor", "Reticle", "ReticleColor", "reticlecolor", "The reticle colour is not a setting."},
    {"PositionSensitivityX", "Position", "PositionSensitivityX", "positionsensitivityx", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"PositionSensitivityY", "Position", "PositionSensitivityY", "positionsensitivityy", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"PositionSensitivityZ", "Position", "PositionSensitivityZ", "positionsensitivityz", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"InvertPositionX", "Inversion", "InvertPositionX", "invertpositionx", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"InvertPositionY", "Inversion", "InvertPositionY", "invertpositiony", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"InvertPositionZ", "Inversion", "InvertPositionZ", "invertpositionz", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"PositionToggleKey", "Hotkeys", "PositionToggleKey", "positiontogglekey", "CycleTrackingModeKey is the hotkey that switches positional tracking."},
    {"ReticleToggleKey", "Hotkeys", "ReticleToggleKey", "reticletogglekey", "The reticle has no toggle key."},
    {"RecenterKey", "Hotkeys", "RecenterKey", "recenterkey", "The mod keeps no centre of its own: centre the view in your tracker app."},
};

inline constexpr std::size_t kNonCanonicalConceptCount =
    sizeof(kNonCanonicalConcepts) / sizeof(kNonCanonicalConcepts[0]);

/// A spelling of a setting the canonical format does not write that is no concept (the schema's
/// non_canonical_keys). ResolveConfigKey does not know it, so the flat readers never read it.
/// `normalized` is the spelling under NormalizeConfigKey; `reason` is the line a player is shown
/// for such a key.
struct NonCanonicalKey {
    const char* name;
    const char* normalized;
    const char* reason;
};

inline constexpr NonCanonicalKey kNonCanonicalKeys[] = {
    {"Sensitivity", "rotscale", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "yawgain", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "pitchgain", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "rollgain", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "positionsensitivity", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "sensitivity", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "rotationsensitivity", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "rotationmultiplier", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "rotationgain", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "positionmultiplier", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "positiongain", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Sensitivity", "leanscale", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Inversion", "signyaw", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"Inversion", "signpitch", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"Inversion", "signroll", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"Inversion", "signx", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"Inversion", "signy", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"Inversion", "signz", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"Deadzone", "deadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "deadzonedeg", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "deadzoneyaw", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "deadzonepitch", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "deadzoneroll", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "yawdeadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "pitchdeadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "rolldeadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "enabledeadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "deadzonemin", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "deadzonemax", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "deadband", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "yawdeadband", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "pitchdeadband", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"Deadzone", "rolldeadband", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
    {"ResponseCurve", "responsecurve", "The mod applies the head pose as the tracker sends it, with no response curve of its own."},
    {"ResponseCurve", "yawcurve", "The mod applies the head pose as the tracker sends it, with no response curve of its own."},
    {"ResponseCurve", "pitchcurve", "The mod applies the head pose as the tracker sends it, with no response curve of its own."},
    {"ResponseCurve", "rollcurve", "The mod applies the head pose as the tracker sends it, with no response curve of its own."},
    {"ResponseCurve", "sensitivitycurve", "The mod applies the head pose as the tracker sends it, with no response curve of its own."},
    {"ResponseCurve", "curvestrength", "The mod applies the head pose as the tracker sends it, with no response curve of its own."},
    {"PositionScale", "positionscale", "The mod converts your head movement to the game's units itself, so the scale is not a setting."},
    {"PositionScale", "positionscaleuu", "The mod converts your head movement to the game's units itself, so the scale is not a setting."},
    {"PositionScale", "posscale", "The mod converts your head movement to the game's units itself, so the scale is not a setting."},
    {"PositionScale", "worldscale", "The mod converts your head movement to the game's units itself, so the scale is not a setting."},
    {"PositionScale", "unitspermeter", "The mod converts your head movement to the game's units itself, so the scale is not a setting."},
    {"PositionScale", "unitspermetre", "The mod converts your head movement to the game's units itself, so the scale is not a setting."},
    {"PositionScale", "worldunitspermeter", "The mod converts your head movement to the game's units itself, so the scale is not a setting."},
    {"PositionScale", "worldunitspermetre", "The mod converts your head movement to the game's units itself, so the scale is not a setting."},
};

inline constexpr std::size_t kNonCanonicalKeyCount = sizeof(kNonCanonicalKeys) / sizeof(kNonCanonicalKeys[0]);

/// A section that holds only settings the canonical format does not write (a group's
/// `sections` in the schema's non_canonical_keys), so every key in it is the group's. Matched
/// ASCII case-insensitively; `reason` is the line a player is shown for a key in it.
struct NonCanonicalSection {
    const char* name;
    const char* section;
    const char* reason;
};

inline constexpr NonCanonicalSection kNonCanonicalSections[] = {
    {"Sensitivity", "Sensitivity", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own."},
    {"Inversion", "Inversion", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own."},
    {"Deadzone", "Deadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own."},
};

inline constexpr std::size_t kNonCanonicalSectionCount =
    sizeof(kNonCanonicalSections) / sizeof(kNonCanonicalSections[0]);

}  // namespace cameraunlock::config::schema
