// Generated by scripts/generate-config-schema.mjs from data/config-schema.json.
// Do not edit. Edit the schema and re-run the generator; `pixi run check-config-schema`
// fails the build when this file is stale.

#pragma once

#include <cstddef>
#include <string>

namespace cameraunlock {
namespace config_keys {

inline constexpr const char* kUdpPort = "udpport";
inline constexpr const char* kEnableOnStartup = "enableonstartup";
inline constexpr const char* kYawSensitivity = "yawsensitivity";
inline constexpr const char* kPitchSensitivity = "pitchsensitivity";
inline constexpr const char* kRollSensitivity = "rollsensitivity";
inline constexpr const char* kInvertYaw = "invertyaw";
inline constexpr const char* kInvertPitch = "invertpitch";
inline constexpr const char* kInvertRoll = "invertroll";
inline constexpr const char* kLocalSmoothing = "localsmoothing";
inline constexpr const char* kRemoteSmoothing = "remotesmoothing";
inline constexpr const char* kWorldSpaceYaw = "worldspaceyaw";
inline constexpr const char* kAimDecoupling = "aimdecoupling";
inline constexpr const char* kShowReticle = "showreticle";
inline constexpr const char* kReticleColor = "reticlecolor";
inline constexpr const char* kRotationEnabled = "rotationenabled";
inline constexpr const char* kDataFreshnessMs = "datafreshnessms";
inline constexpr const char* kPositionEnabled = "positionenabled";
inline constexpr const char* kPositionAllowed = "positionallowed";
inline constexpr const char* kTrueFreeLook = "truefreelook";
inline constexpr const char* kPositionSensitivityX = "positionsensitivityx";
inline constexpr const char* kPositionSensitivityY = "positionsensitivityy";
inline constexpr const char* kPositionSensitivityZ = "positionsensitivityz";
inline constexpr const char* kPositionLimitX = "positionlimitx";
inline constexpr const char* kPositionLimitY = "positionlimity";
inline constexpr const char* kPositionLimitYDown = "positionlimitydown";
inline constexpr const char* kPositionLimitZ = "positionlimitz";
inline constexpr const char* kPositionLimitZBack = "positionlimitzback";
inline constexpr const char* kCollisionEnabled = "collisionenabled";
inline constexpr const char* kCollisionMargin = "collisionmargin";
inline constexpr const char* kCollisionChannel = "collisionchannel";
inline constexpr const char* kCollisionReleaseSmoothing = "collisionreleasesmoothing";
inline constexpr const char* kInvertPositionX = "invertpositionx";
inline constexpr const char* kInvertPositionY = "invertpositiony";
inline constexpr const char* kInvertPositionZ = "invertpositionz";
inline constexpr const char* kTrackerPivotForward = "trackerpivotforward";
inline constexpr const char* kTrackerPivotUp = "trackerpivotup";
inline constexpr const char* kToggleKey = "togglekey";
inline constexpr const char* kPositionToggleKey = "positiontogglekey";
inline constexpr const char* kReticleToggleKey = "reticletogglekey";
inline constexpr const char* kCycleTrackingModeKey = "cycletrackingmodekey";
inline constexpr const char* kYawModeKey = "yawmodekey";
inline constexpr const char* kTrueFreeLookKey = "truefreelookkey";
inline constexpr const char* kRecenterKey = "recenterkey";
inline constexpr const char* kLightFollowsHead = "lightfollowshead";
inline constexpr const char* kLightMultiplier = "lightmultiplier";

inline constexpr const char* kSmoothing = "smoothing";

}  // namespace config_keys

/// One accepted spelling of a config key. `normalized` is the lookup form (lowercased,
/// '_' and '-' stripped); `canonical` is the name every spelling of the concept resolves
/// to, matching ConfigKeySchema.Keys on the C# side.
struct ConfigKeyAlias {
    const char* normalized;
    const char* canonical;
    bool retired;
};

inline constexpr ConfigKeyAlias kConfigKeyAliases[] = {
    { "aimdecouple", "aimdecoupling", false },
    { "aimdecoupling", "aimdecoupling", false },
    { "autoenable", "enableonstartup", false },
    { "cameracollision", "collisionenabled", false },
    { "cameracollisionradius", "collisionmargin", false },
    { "centerkey", "recenterkey", false },
    { "centrekey", "recenterkey", false },
    { "clamplean", "collisionenabled", false },
    { "collisionchannel", "collisionchannel", false },
    { "collisionenabled", "collisionenabled", false },
    { "collisionmargin", "collisionmargin", false },
    { "collisionradius", "collisionmargin", false },
    { "collisionrelease", "collisionreleasesmoothing", false },
    { "collisionreleasesmoothing", "collisionreleasesmoothing", false },
    { "collisionskin", "collisionmargin", false },
    { "collisiontracechannel", "collisionchannel", false },
    { "compensatecrosshair", "showreticle", false },
    { "compensateflashlight", "lightfollowshead", false },
    { "compensatereticle", "showreticle", false },
    { "crosshaircolor", "reticlecolor", false },
    { "crosshaircolour", "reticlecolor", false },
    { "crosshairtogglekey", "reticletogglekey", false },
    { "cyclemode", "cycletrackingmodekey", false },
    { "cyclemodekey", "cycletrackingmodekey", false },
    { "cycletrackingmode", "cycletrackingmodekey", false },
    { "cycletrackingmodekey", "cycletrackingmodekey", false },
    { "datafreshnessms", "datafreshnessms", false },
    { "decoupleaim", "aimdecoupling", false },
    { "decoupledaim", "aimdecoupling", false },
    { "drawreticle", "showreticle", false },
    { "enable6dof", "positionenabled", false },
    { "enableaimdecoupling", "aimdecoupling", false },
    { "enableatstartup", "enableonstartup", false },
    { "enabledonstartup", "enableonstartup", false },
    { "enableheadtracking", "enableonstartup", false },
    { "enablekey", "togglekey", false },
    { "enableonstartup", "enableonstartup", false },
    { "enableposition", "positionenabled", false },
    { "enablepositiontracking", "positionenabled", false },
    { "flashlightfollowshead", "lightfollowshead", false },
    { "flashlightmultiplier", "lightmultiplier", false },
    { "flashlightscale", "lightmultiplier", false },
    { "horizonlock", "worldspaceyaw", false },
    { "horizonlockedyaw", "worldspaceyaw", false },
    { "invertpitch", "invertpitch", false },
    { "invertpitchaxis", "invertpitch", false },
    { "invertpositionx", "invertpositionx", false },
    { "invertpositiony", "invertpositiony", false },
    { "invertpositionz", "invertpositionz", false },
    { "invertroll", "invertroll", false },
    { "invertrollaxis", "invertroll", false },
    { "inverttrackerx", "invertpositionx", false },
    { "inverttrackery", "invertpositiony", false },
    { "inverttrackerz", "invertpositionz", false },
    { "invertx", "invertpositionx", false },
    { "inverty", "invertpositiony", false },
    { "invertyaw", "invertyaw", false },
    { "invertyawaxis", "invertyaw", false },
    { "invertz", "invertpositionz", false },
    { "keycyclemode", "cycletrackingmodekey", false },
    { "keytoggle", "togglekey", false },
    { "keyyawmode", "yawmodekey", false },
    { "leanclamprelease", "collisionreleasesmoothing", false },
    { "leancollision", "collisionenabled", false },
    { "leancollisionchannel", "collisionchannel", false },
    { "leancollisionenabled", "collisionenabled", false },
    { "leancollisionmargin", "collisionmargin", false },
    { "leanreleasesmoothing", "collisionreleasesmoothing", false },
    { "lightfollowshead", "lightfollowshead", false },
    { "lightmultiplier", "lightmultiplier", false },
    { "limitdown", "positionlimitydown", false },
    { "limitx", "positionlimitx", false },
    { "limity", "positionlimity", false },
    { "limitydown", "positionlimitydown", false },
    { "limityup", "positionlimity", false },
    { "limitz", "positionlimitz", false },
    { "limitzback", "positionlimitzback", false },
    { "limitzbackward", "positionlimitzback", false },
    { "limitzforward", "positionlimitz", false },
    { "limitzfwd", "positionlimitz", false },
    { "listenport", "udpport", false },
    { "localsmoothing", "localsmoothing", false },
    { "lockhorizon", "worldspaceyaw", false },
    { "maxx", "positionlimitx", false },
    { "maxy", "positionlimity", false },
    { "maxydown", "positionlimitydown", false },
    { "maxz", "positionlimitz", false },
    { "maxzback", "positionlimitzback", false },
    { "modecycle", "cycletrackingmodekey", false },
    { "modekey", "cycletrackingmodekey", false },
    { "movecrosshair", "showreticle", false },
    { "neckmodelforward", "trackerpivotforward", false },
    { "neckmodelheight", "trackerpivotup", false },
    { "neckpivotforward", "trackerpivotforward", false },
    { "neckpivotup", "trackerpivotup", false },
    { "opentrackport", "udpport", false },
    { "pitchinvert", "invertpitch", false },
    { "pitchmultiplier", "pitchsensitivity", false },
    { "pitchscale", "pitchsensitivity", false },
    { "pitchsens", "pitchsensitivity", false },
    { "pitchsensitivity", "pitchsensitivity", false },
    { "pivotarm", "trackerpivotforward", false },
    { "pivotforward", "trackerpivotforward", false },
    { "pivotup", "trackerpivotup", false },
    { "port", "udpport", false },
    { "positionallowed", "positionallowed", false },
    { "positionenabled", "positionenabled", false },
    { "positioninvertx", "invertpositionx", false },
    { "positioninverty", "invertpositiony", false },
    { "positioninvertz", "invertpositionz", false },
    { "positionkey", "positiontogglekey", false },
    { "positionlimitx", "positionlimitx", false },
    { "positionlimity", "positionlimity", false },
    { "positionlimitydown", "positionlimitydown", false },
    { "positionlimityup", "positionlimity", false },
    { "positionlimitz", "positionlimitz", false },
    { "positionlimitzback", "positionlimitzback", false },
    { "positionlimitzbackward", "positionlimitzback", false },
    { "positionlimitzforward", "positionlimitz", false },
    { "positionlimitzfwd", "positionlimitz", false },
    { "positionmaxx", "positionlimitx", false },
    { "positionmaxy", "positionlimity", false },
    { "positionmaxydown", "positionlimitydown", false },
    { "positionmaxz", "positionlimitz", false },
    { "positionmaxzback", "positionlimitzback", false },
    { "positionsensitivityx", "positionsensitivityx", false },
    { "positionsensitivityy", "positionsensitivityy", false },
    { "positionsensitivityz", "positionsensitivityz", false },
    { "positionsensx", "positionsensitivityx", false },
    { "positionsensy", "positionsensitivityy", false },
    { "positionsensz", "positionsensitivityz", false },
    { "positiontogglekey", "positiontogglekey", false },
    { "positiontracking", "positionenabled", false },
    { "positiontrackingenabled", "positionenabled", false },
    { "recenterkey", "recenterkey", false },
    { "recentrekey", "recenterkey", false },
    { "remotesmoothing", "remotesmoothing", false },
    { "reticlecolor", "reticlecolor", false },
    { "reticlecolour", "reticlecolor", false },
    { "reticleenabled", "showreticle", false },
    { "reticlekey", "reticletogglekey", false },
    { "reticletoggle", "reticletogglekey", false },
    { "reticletogglekey", "reticletogglekey", false },
    { "rollinvert", "invertroll", false },
    { "rollmultiplier", "rollsensitivity", false },
    { "rollscale", "rollsensitivity", false },
    { "rollsens", "rollsensitivity", false },
    { "rollsensitivity", "rollsensitivity", false },
    { "rotationenabled", "rotationenabled", false },
    { "sensitivitypitch", "pitchsensitivity", false },
    { "sensitivityroll", "rollsensitivity", false },
    { "sensitivityx", "positionsensitivityx", false },
    { "sensitivityy", "positionsensitivityy", false },
    { "sensitivityyaw", "yawsensitivity", false },
    { "sensitivityz", "positionsensitivityz", false },
    { "sensx", "positionsensitivityx", false },
    { "sensy", "positionsensitivityy", false },
    { "sensz", "positionsensitivityz", false },
    { "showcrosshair", "showreticle", false },
    { "showdecoupledcrosshair", "showreticle", false },
    { "showdecoupledreticle", "showreticle", false },
    { "showreticle", "showreticle", false },
    { "sixdofenabled", "positionenabled", false },
    { "sixdoftogglekey", "positiontogglekey", false },
    { "smoothing", "smoothing", true },
    { "smoothingfactor", "smoothing", true },
    { "smoothinglocal", "localsmoothing", false },
    { "smoothingremote", "remotesmoothing", false },
    { "startenabled", "enableonstartup", false },
    { "toggle", "togglekey", false },
    { "togglecrosshairkey", "reticletogglekey", false },
    { "togglekey", "togglekey", false },
    { "togglepositionkey", "positiontogglekey", false },
    { "togglereticlekey", "reticletogglekey", false },
    { "toggletracking", "togglekey", false },
    { "toggletrackingkey", "togglekey", false },
    { "toggleyawkey", "yawmodekey", false },
    { "toggleyawmode", "yawmodekey", false },
    { "toggleyawmodekey", "yawmodekey", false },
    { "tracechannel", "collisionchannel", false },
    { "trackerpivot", "trackerpivotforward", false },
    { "trackerpivotforward", "trackerpivotforward", false },
    { "trackerpivotup", "trackerpivotup", false },
    { "trackingmodekey", "cycletrackingmodekey", false },
    { "trackingport", "udpport", false },
    { "trackingtogglekey", "togglekey", false },
    { "truefreelook", "truefreelook", false },
    { "truefreelookkey", "truefreelookkey", false },
    { "udpport", "udpport", false },
    { "worldlockedyaw", "worldspaceyaw", false },
    { "worldspaceyaw", "worldspaceyaw", false },
    { "worldyaw", "worldspaceyaw", false },
    { "worldyawkey", "yawmodekey", false },
    { "xsensitivity", "positionsensitivityx", false },
    { "yawinvert", "invertyaw", false },
    { "yawmode", "yawmodekey", false },
    { "yawmodekey", "yawmodekey", false },
    { "yawmultiplier", "yawsensitivity", false },
    { "yawscale", "yawsensitivity", false },
    { "yawsens", "yawsensitivity", false },
    { "yawsensitivity", "yawsensitivity", false },
    { "ysensitivity", "positionsensitivityy", false },
    { "zsensitivity", "positionsensitivityz", false },
};

inline constexpr size_t kConfigKeyAliasCount = sizeof(kConfigKeyAliases) / sizeof(kConfigKeyAliases[0]);

enum class ConfigValueType { kInt, kFloat, kBool, kString, kColor };

/// The default data/config-schema.json declares for one concept: what a key means when a
/// file leaves it out. Only the member `type` names carries the default; the rest are
/// zero, and `string_value` is nullptr unless `type` is kString.
struct ConfigConceptDefault {
    const char* id;
    const char* canonical;
    ConfigValueType type;
    int int_value;
    float float_value;
    bool bool_value;
    const char* string_value;
    float color_value[4];
};

inline constexpr ConfigConceptDefault kConfigConceptDefaults[] = {
    { "UdpPort", config_keys::kUdpPort, ConfigValueType::kInt, 4242, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "EnableOnStartup", config_keys::kEnableOnStartup, ConfigValueType::kBool, 0, 0.0f, true, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "YawSensitivity", config_keys::kYawSensitivity, ConfigValueType::kFloat, 0, 1.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PitchSensitivity", config_keys::kPitchSensitivity, ConfigValueType::kFloat, 0, 1.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "RollSensitivity", config_keys::kRollSensitivity, ConfigValueType::kFloat, 0, 1.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "InvertYaw", config_keys::kInvertYaw, ConfigValueType::kBool, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "InvertPitch", config_keys::kInvertPitch, ConfigValueType::kBool, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "InvertRoll", config_keys::kInvertRoll, ConfigValueType::kBool, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "LocalSmoothing", config_keys::kLocalSmoothing, ConfigValueType::kFloat, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "RemoteSmoothing", config_keys::kRemoteSmoothing, ConfigValueType::kFloat, 0, 0.15f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "WorldSpaceYaw", config_keys::kWorldSpaceYaw, ConfigValueType::kBool, 0, 0.0f, true, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "AimDecoupling", config_keys::kAimDecoupling, ConfigValueType::kBool, 0, 0.0f, true, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "ShowReticle", config_keys::kShowReticle, ConfigValueType::kBool, 0, 0.0f, true, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "ReticleColor", config_keys::kReticleColor, ConfigValueType::kColor, 0, 0.0f, false, nullptr, {1.0f, 1.0f, 1.0f, 1.0f} },
    { "RotationEnabled", config_keys::kRotationEnabled, ConfigValueType::kBool, 0, 0.0f, true, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "DataFreshnessMs", config_keys::kDataFreshnessMs, ConfigValueType::kInt, 500, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionEnabled", config_keys::kPositionEnabled, ConfigValueType::kBool, 0, 0.0f, true, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionAllowed", config_keys::kPositionAllowed, ConfigValueType::kBool, 0, 0.0f, true, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "TrueFreeLook", config_keys::kTrueFreeLook, ConfigValueType::kBool, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionSensitivityX", config_keys::kPositionSensitivityX, ConfigValueType::kFloat, 0, 1.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionSensitivityY", config_keys::kPositionSensitivityY, ConfigValueType::kFloat, 0, 1.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionSensitivityZ", config_keys::kPositionSensitivityZ, ConfigValueType::kFloat, 0, 1.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionLimitX", config_keys::kPositionLimitX, ConfigValueType::kFloat, 0, 0.3f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionLimitY", config_keys::kPositionLimitY, ConfigValueType::kFloat, 0, 0.2f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionLimitYDown", config_keys::kPositionLimitYDown, ConfigValueType::kFloat, 0, 0.2f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionLimitZ", config_keys::kPositionLimitZ, ConfigValueType::kFloat, 0, 0.4f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionLimitZBack", config_keys::kPositionLimitZBack, ConfigValueType::kFloat, 0, 0.1f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "CollisionEnabled", config_keys::kCollisionEnabled, ConfigValueType::kBool, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "CollisionMargin", config_keys::kCollisionMargin, ConfigValueType::kFloat, 0, 0.1f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "CollisionChannel", config_keys::kCollisionChannel, ConfigValueType::kInt, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "CollisionReleaseSmoothing", config_keys::kCollisionReleaseSmoothing, ConfigValueType::kFloat, 0, 0.9f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "InvertPositionX", config_keys::kInvertPositionX, ConfigValueType::kBool, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "InvertPositionY", config_keys::kInvertPositionY, ConfigValueType::kBool, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "InvertPositionZ", config_keys::kInvertPositionZ, ConfigValueType::kBool, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "TrackerPivotForward", config_keys::kTrackerPivotForward, ConfigValueType::kFloat, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "TrackerPivotUp", config_keys::kTrackerPivotUp, ConfigValueType::kFloat, 0, 0.0f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "ToggleKey", config_keys::kToggleKey, ConfigValueType::kString, 0, 0.0f, false, "End", {0.0f, 0.0f, 0.0f, 0.0f} },
    { "PositionToggleKey", config_keys::kPositionToggleKey, ConfigValueType::kString, 0, 0.0f, false, "PageUp", {0.0f, 0.0f, 0.0f, 0.0f} },
    { "ReticleToggleKey", config_keys::kReticleToggleKey, ConfigValueType::kString, 0, 0.0f, false, "Insert", {0.0f, 0.0f, 0.0f, 0.0f} },
    { "CycleTrackingModeKey", config_keys::kCycleTrackingModeKey, ConfigValueType::kString, 0, 0.0f, false, "", {0.0f, 0.0f, 0.0f, 0.0f} },
    { "YawModeKey", config_keys::kYawModeKey, ConfigValueType::kString, 0, 0.0f, false, "PageDown", {0.0f, 0.0f, 0.0f, 0.0f} },
    { "TrueFreeLookKey", config_keys::kTrueFreeLookKey, ConfigValueType::kString, 0, 0.0f, false, "Insert", {0.0f, 0.0f, 0.0f, 0.0f} },
    { "RecenterKey", config_keys::kRecenterKey, ConfigValueType::kString, 0, 0.0f, false, "Home", {0.0f, 0.0f, 0.0f, 0.0f} },
    { "LightFollowsHead", config_keys::kLightFollowsHead, ConfigValueType::kBool, 0, 0.0f, true, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
    { "LightMultiplier", config_keys::kLightMultiplier, ConfigValueType::kFloat, 0, 1.5f, false, nullptr, {0.0f, 0.0f, 0.0f, 0.0f} },
};

inline constexpr size_t kConfigConceptDefaultCount =
    sizeof(kConfigConceptDefaults) / sizeof(kConfigConceptDefaults[0]);

/// Lowercases a key and strips '_' and '-'. Applied to both sides of a lookup.
inline std::string NormalizeConfigKey(const std::string& key) {
    std::string out;
    out.reserve(key.size());
    for (char c : key) {
        if (c == '_' || c == '-') continue;
        if (c >= 'A' && c <= 'Z') c = static_cast<char>(c - 'A' + 'a');
        out.push_back(c);
    }
    return out;
}

/// Resolves any accepted spelling to its canonical normalized name, or nullptr when the
/// key belongs to no concept in the schema. The returned pointer is static storage.
inline const char* ResolveConfigKey(const std::string& key) {
    const std::string normalized = NormalizeConfigKey(key);
    for (size_t i = 0; i < kConfigKeyAliasCount; ++i) {
        if (normalized == kConfigKeyAliases[i].normalized) return kConfigKeyAliases[i].canonical;
    }
    return nullptr;
}

/// True when the canonical name names a retired concept: it parses, and is ignored.
inline bool IsRetiredConfigKey(const char* canonical_key) {
    if (canonical_key == nullptr) return false;
    for (size_t i = 0; i < kConfigKeyAliasCount; ++i) {
        if (kConfigKeyAliases[i].retired && std::string(canonical_key) == kConfigKeyAliases[i].canonical) {
            return true;
        }
    }
    return false;
}

}  // namespace cameraunlock
