// Generated by scripts/generate-config-schema.mjs from data/config-schema.json.
// Do not edit. Edit the schema and re-run the generator; `pixi run check-config-schema`
// fails the build when this file is stale.

using System.Collections.Generic;
using System.Text;

namespace CameraUnlock.Core.Config
{
    /// <summary>
    /// The canonical config-key vocabulary, shared with the C++ half of the library.
    /// Matching is section-less and case-insensitive: <see cref="Normalize"/> lowercases a
    /// key and strips '_' and '-', so Network.UDPPort, udp_port and Udp-Port all resolve to
    /// the same canonical name.
    /// </summary>
    public static class ConfigKeySchema
    {
        /// <summary>Canonical names, as returned by <see cref="Resolve"/>.</summary>
        public static class Keys
        {
            public const string UdpPort = "udpport";
            public const string EnableOnStartup = "enableonstartup";
            public const string YawSensitivity = "yawsensitivity";
            public const string PitchSensitivity = "pitchsensitivity";
            public const string RollSensitivity = "rollsensitivity";
            public const string InvertYaw = "invertyaw";
            public const string InvertPitch = "invertpitch";
            public const string InvertRoll = "invertroll";
            public const string LocalSmoothing = "localsmoothing";
            public const string RemoteSmoothing = "remotesmoothing";
            public const string WorldSpaceYaw = "worldspaceyaw";
            public const string AimDecoupling = "aimdecoupling";
            public const string ShowReticle = "showreticle";
            public const string ReticleColor = "reticlecolor";
            public const string PositionEnabled = "positionenabled";
            public const string PositionSensitivityX = "positionsensitivityx";
            public const string PositionSensitivityY = "positionsensitivityy";
            public const string PositionSensitivityZ = "positionsensitivityz";
            public const string PositionLimitX = "positionlimitx";
            public const string PositionLimitY = "positionlimity";
            public const string PositionLimitYDown = "positionlimitydown";
            public const string PositionLimitZ = "positionlimitz";
            public const string PositionLimitZBack = "positionlimitzback";
            public const string InvertPositionX = "invertpositionx";
            public const string InvertPositionY = "invertpositiony";
            public const string InvertPositionZ = "invertpositionz";
            public const string TrackerPivotForward = "trackerpivotforward";
            public const string TrackerPivotUp = "trackerpivotup";
            public const string ToggleKey = "togglekey";
            public const string PositionToggleKey = "positiontogglekey";
            public const string ReticleToggleKey = "reticletogglekey";
            public const string CycleTrackingModeKey = "cycletrackingmodekey";
            public const string YawModeKey = "yawmodekey";
            public const string RecenterKey = "recenterkey";

            public const string Smoothing = "smoothing";
        }

        private static readonly Dictionary<string, string> Aliases = new Dictionary<string, string>
        {
            { "aimdecouple", "aimdecoupling" },
            { "aimdecoupling", "aimdecoupling" },
            { "autoenable", "enableonstartup" },
            { "centerkey", "recenterkey" },
            { "centrekey", "recenterkey" },
            { "compensatecrosshair", "showreticle" },
            { "compensatereticle", "showreticle" },
            { "crosshaircolor", "reticlecolor" },
            { "crosshaircolour", "reticlecolor" },
            { "crosshairtogglekey", "reticletogglekey" },
            { "cyclemode", "cycletrackingmodekey" },
            { "cyclemodekey", "cycletrackingmodekey" },
            { "cycletrackingmode", "cycletrackingmodekey" },
            { "cycletrackingmodekey", "cycletrackingmodekey" },
            { "decoupleaim", "aimdecoupling" },
            { "decoupledaim", "aimdecoupling" },
            { "drawreticle", "showreticle" },
            { "enable6dof", "positionenabled" },
            { "enableaimdecoupling", "aimdecoupling" },
            { "enableatstartup", "enableonstartup" },
            { "enabledonstartup", "enableonstartup" },
            { "enableheadtracking", "enableonstartup" },
            { "enablekey", "togglekey" },
            { "enableonstartup", "enableonstartup" },
            { "enableposition", "positionenabled" },
            { "enablepositiontracking", "positionenabled" },
            { "horizonlock", "worldspaceyaw" },
            { "horizonlockedyaw", "worldspaceyaw" },
            { "invertpitch", "invertpitch" },
            { "invertpitchaxis", "invertpitch" },
            { "invertpositionx", "invertpositionx" },
            { "invertpositiony", "invertpositiony" },
            { "invertpositionz", "invertpositionz" },
            { "invertroll", "invertroll" },
            { "invertrollaxis", "invertroll" },
            { "inverttrackerx", "invertpositionx" },
            { "inverttrackery", "invertpositiony" },
            { "inverttrackerz", "invertpositionz" },
            { "invertx", "invertpositionx" },
            { "inverty", "invertpositiony" },
            { "invertyaw", "invertyaw" },
            { "invertyawaxis", "invertyaw" },
            { "invertz", "invertpositionz" },
            { "keycyclemode", "cycletrackingmodekey" },
            { "keytoggle", "togglekey" },
            { "keyyawmode", "yawmodekey" },
            { "limitdown", "positionlimitydown" },
            { "limitx", "positionlimitx" },
            { "limity", "positionlimity" },
            { "limitydown", "positionlimitydown" },
            { "limityup", "positionlimity" },
            { "limitz", "positionlimitz" },
            { "limitzback", "positionlimitzback" },
            { "limitzbackward", "positionlimitzback" },
            { "limitzforward", "positionlimitz" },
            { "limitzfwd", "positionlimitz" },
            { "listenport", "udpport" },
            { "localsmoothing", "localsmoothing" },
            { "lockhorizon", "worldspaceyaw" },
            { "maxx", "positionlimitx" },
            { "maxy", "positionlimity" },
            { "maxydown", "positionlimitydown" },
            { "maxz", "positionlimitz" },
            { "maxzback", "positionlimitzback" },
            { "modecycle", "cycletrackingmodekey" },
            { "modekey", "cycletrackingmodekey" },
            { "movecrosshair", "showreticle" },
            { "neckmodelforward", "trackerpivotforward" },
            { "neckmodelheight", "trackerpivotup" },
            { "neckpivotforward", "trackerpivotforward" },
            { "neckpivotup", "trackerpivotup" },
            { "opentrackport", "udpport" },
            { "pitchinvert", "invertpitch" },
            { "pitchmultiplier", "pitchsensitivity" },
            { "pitchscale", "pitchsensitivity" },
            { "pitchsens", "pitchsensitivity" },
            { "pitchsensitivity", "pitchsensitivity" },
            { "pivotarm", "trackerpivotforward" },
            { "pivotforward", "trackerpivotforward" },
            { "pivotup", "trackerpivotup" },
            { "port", "udpport" },
            { "positionenabled", "positionenabled" },
            { "positioninvertx", "invertpositionx" },
            { "positioninverty", "invertpositiony" },
            { "positioninvertz", "invertpositionz" },
            { "positionkey", "positiontogglekey" },
            { "positionlimitx", "positionlimitx" },
            { "positionlimity", "positionlimity" },
            { "positionlimitydown", "positionlimitydown" },
            { "positionlimityup", "positionlimity" },
            { "positionlimitz", "positionlimitz" },
            { "positionlimitzback", "positionlimitzback" },
            { "positionlimitzbackward", "positionlimitzback" },
            { "positionlimitzforward", "positionlimitz" },
            { "positionlimitzfwd", "positionlimitz" },
            { "positionmaxx", "positionlimitx" },
            { "positionmaxy", "positionlimity" },
            { "positionmaxydown", "positionlimitydown" },
            { "positionmaxz", "positionlimitz" },
            { "positionmaxzback", "positionlimitzback" },
            { "positionsensitivityx", "positionsensitivityx" },
            { "positionsensitivityy", "positionsensitivityy" },
            { "positionsensitivityz", "positionsensitivityz" },
            { "positionsensx", "positionsensitivityx" },
            { "positionsensy", "positionsensitivityy" },
            { "positionsensz", "positionsensitivityz" },
            { "positiontogglekey", "positiontogglekey" },
            { "positiontracking", "positionenabled" },
            { "positiontrackingenabled", "positionenabled" },
            { "recenterkey", "recenterkey" },
            { "recentrekey", "recenterkey" },
            { "remotesmoothing", "remotesmoothing" },
            { "reticlecolor", "reticlecolor" },
            { "reticlecolour", "reticlecolor" },
            { "reticleenabled", "showreticle" },
            { "reticlekey", "reticletogglekey" },
            { "reticletoggle", "reticletogglekey" },
            { "reticletogglekey", "reticletogglekey" },
            { "rollinvert", "invertroll" },
            { "rollmultiplier", "rollsensitivity" },
            { "rollscale", "rollsensitivity" },
            { "rollsens", "rollsensitivity" },
            { "rollsensitivity", "rollsensitivity" },
            { "sensitivitypitch", "pitchsensitivity" },
            { "sensitivityroll", "rollsensitivity" },
            { "sensitivityx", "positionsensitivityx" },
            { "sensitivityy", "positionsensitivityy" },
            { "sensitivityyaw", "yawsensitivity" },
            { "sensitivityz", "positionsensitivityz" },
            { "sensx", "positionsensitivityx" },
            { "sensy", "positionsensitivityy" },
            { "sensz", "positionsensitivityz" },
            { "showcrosshair", "showreticle" },
            { "showdecoupledcrosshair", "showreticle" },
            { "showdecoupledreticle", "showreticle" },
            { "showreticle", "showreticle" },
            { "sixdofenabled", "positionenabled" },
            { "sixdoftogglekey", "positiontogglekey" },
            { "smoothing", "smoothing" },
            { "smoothingfactor", "smoothing" },
            { "smoothinglocal", "localsmoothing" },
            { "smoothingremote", "remotesmoothing" },
            { "startenabled", "enableonstartup" },
            { "toggle", "togglekey" },
            { "togglecrosshairkey", "reticletogglekey" },
            { "togglekey", "togglekey" },
            { "togglepositionkey", "positiontogglekey" },
            { "togglereticlekey", "reticletogglekey" },
            { "toggletracking", "togglekey" },
            { "toggletrackingkey", "togglekey" },
            { "toggleyawkey", "yawmodekey" },
            { "toggleyawmode", "yawmodekey" },
            { "toggleyawmodekey", "yawmodekey" },
            { "trackerpivot", "trackerpivotforward" },
            { "trackerpivotforward", "trackerpivotforward" },
            { "trackerpivotup", "trackerpivotup" },
            { "trackingmodekey", "cycletrackingmodekey" },
            { "trackingport", "udpport" },
            { "trackingtogglekey", "togglekey" },
            { "udpport", "udpport" },
            { "worldlockedyaw", "worldspaceyaw" },
            { "worldspaceyaw", "worldspaceyaw" },
            { "worldyaw", "worldspaceyaw" },
            { "worldyawkey", "yawmodekey" },
            { "xsensitivity", "positionsensitivityx" },
            { "yawinvert", "invertyaw" },
            { "yawmode", "yawmodekey" },
            { "yawmodekey", "yawmodekey" },
            { "yawmultiplier", "yawsensitivity" },
            { "yawscale", "yawsensitivity" },
            { "yawsens", "yawsensitivity" },
            { "yawsensitivity", "yawsensitivity" },
            { "ysensitivity", "positionsensitivityy" },
            { "zsensitivity", "positionsensitivityz" },
        };

        private static readonly HashSet<string> Retired = new HashSet<string>
        {
            "smoothing",
        };

        /// <summary>
        /// Strips '_' and '-' and folds ASCII A-Z to lower case. Applied to both sides of a
        /// lookup.
        /// <para>
        /// Deliberately not <c>ToLowerInvariant</c>: full Unicode case folding maps
        /// U+212A KELVIN SIGN onto 'k', so a key spelled with one bound here and was
        /// ignored by the C++ table, which folds A-Z and nothing else. Every spelling in
        /// the schema is ASCII, so nothing accepted by the table needs the wider fold.
        /// </para>
        /// </summary>
        public static string Normalize(string key)
        {
            if (key == null) return null;
            var normalized = new StringBuilder(key.Length);
            for (int i = 0; i < key.Length; i++)
            {
                char c = key[i];
                if (c == '_' || c == '-') continue;
                if (c >= 'A' && c <= 'Z') c = (char)(c - 'A' + 'a');
                normalized.Append(c);
            }
            return normalized.ToString();
        }

        /// <summary>
        /// Resolves any accepted spelling to its canonical normalized name, or null when the
        /// key belongs to no concept in the schema.
        /// </summary>
        public static string Resolve(string key)
        {
            string normalized = Normalize(key);
            if (normalized == null) return null;
            string canonical;
            return Aliases.TryGetValue(normalized, out canonical) ? canonical : null;
        }

        /// <summary>
        /// True when the canonical name names a retired concept: it parses, and is ignored.
        /// </summary>
        public static bool IsRetired(string canonicalKey)
        {
            return canonicalKey != null && Retired.Contains(canonicalKey);
        }
    }
}
