// Generated by scripts/generate-config-schema.mjs from data/config-schema.json.
// Do not edit. Edit the schema and re-run the generator; `pixi run check-config-schema`
// fails the build when this file is stale.

using System.Collections.Generic;

namespace CameraUnlock.Core.Config
{
    /// <summary>
    /// The concepts a canonical config file writes: every concept data/config-schema.json marks
    /// canonical, shared with the C++ half of the library as cameraunlock::config::schema. A
    /// config table binds each through its descriptor, whose type fixes the field's type and
    /// whose codec carries the schema's range.
    /// </summary>
    public static class ConfigConcepts
    {
        /// <summary>[Network] UdpPort.</summary>
        public static readonly ConceptDescriptor<int> UdpPort = new ConceptDescriptor<int>(
            "UdpPort", "Network", "UdpPort", ConceptValueFamily.Integer,
            new IntCodec(1, 65535), new[] { "UDP port the mod receives tracker data on (OpenTrack protocol)." }, null);

        /// <summary>[General] EnableOnStartup.</summary>
        public static readonly ConceptDescriptor<bool> EnableOnStartup = new ConceptDescriptor<bool>(
            "EnableOnStartup", "General", "EnableOnStartup", ConceptValueFamily.Bool,
            new BoolCodec(), new[] { "true: head tracking is on when the game starts. ToggleKey turns it on and off." }, null);

        /// <summary>[Smoothing] LocalSmoothing.</summary>
        public static readonly ConceptDescriptor<float> LocalSmoothing = new ConceptDescriptor<float>(
            "LocalSmoothing", "Smoothing", "LocalSmoothing", ConceptValueFamily.Floating,
            new FloatCodec(0f, 1f), new[] { "Smoothing when the tracker runs on this PC. 0 is the least, 1 the most." }, null);

        /// <summary>[Smoothing] RemoteSmoothing.</summary>
        public static readonly ConceptDescriptor<float> RemoteSmoothing = new ConceptDescriptor<float>(
            "RemoteSmoothing", "Smoothing", "RemoteSmoothing", ConceptValueFamily.Floating,
            new FloatCodec(0f, 1f), new[] { "Smoothing when the tracker is another device on the network, such as a phone.", "0 is the least, 1 the most." }, null);

        /// <summary>[General] WorldSpaceYaw.</summary>
        public static readonly ConceptDescriptor<bool> WorldSpaceYaw = new ConceptDescriptor<bool>(
            "WorldSpaceYaw", "General", "WorldSpaceYaw", ConceptValueFamily.Bool,
            new BoolCodec(), new[] { "true: yaw turns around the world's up axis. false: around the camera's own up axis." }, null);

        /// <summary>[General] AimDecoupling.</summary>
        public static readonly ConceptDescriptor<bool> AimDecoupling = new ConceptDescriptor<bool>(
            "AimDecoupling", "General", "AimDecoupling", ConceptValueFamily.Bool,
            new BoolCodec(), new[] { "true: your aim stays with the mouse or controller while your head moves the view." }, null);

        /// <summary>[General] RotationEnabled.</summary>
        public static readonly ConceptDescriptor<bool> RotationEnabled = new ConceptDescriptor<bool>(
            "RotationEnabled", "General", "RotationEnabled", ConceptValueFamily.Bool,
            new BoolCodec(), new[] { "true: turning your head turns the view.", "Tracking mode at startup, with PositionEnabled. The mode hotkey changes both." }, null);

        /// <summary>[General] DataFreshnessMs.</summary>
        public static readonly ConceptDescriptor<int> DataFreshnessMs = new ConceptDescriptor<int>(
            "DataFreshnessMs", "General", "DataFreshnessMs", ConceptValueFamily.Integer,
            new IntCodec(1, 2147483647), new[] { "Milliseconds a tracker packet stays current. Once the tracker has sent nothing", "for this long, the mod stops following it until data arrives again." }, null);

        /// <summary>[Position] PositionEnabled.</summary>
        public static readonly ConceptDescriptor<bool> PositionEnabled = new ConceptDescriptor<bool>(
            "PositionEnabled", "Position", "PositionEnabled", ConceptValueFamily.Bool,
            new BoolCodec(), new[] { "true: moving your head moves the view.", "Tracking mode at startup, with RotationEnabled. The mode hotkey changes both." }, null);

        /// <summary>[Position] PositionAllowed.</summary>
        public static readonly ConceptDescriptor<bool> PositionAllowed = new ConceptDescriptor<bool>(
            "PositionAllowed", "Position", "PositionAllowed", ConceptValueFamily.Bool,
            new BoolCodec(), new[] { "false: head tracking runs rotation only, whatever RotationEnabled and PositionEnabled say,", "and the mode hotkey skips the modes that use position." }, null);

        /// <summary>[Position] TrueFreeLook.</summary>
        public static readonly ConceptDescriptor<bool> TrueFreeLook = new ConceptDescriptor<bool>(
            "TrueFreeLook", "Position", "TrueFreeLook", ConceptValueFamily.Bool,
            new BoolCodec(), new[] { "false: while you aim down the sights, leaning keeps your eye on the sights.", "true: the weapon stays put and your head moves freely around it (true free look)." }, null);

        /// <summary>[Position] PositionLimitX.</summary>
        public static readonly ConceptDescriptor<float> PositionLimitX = new ConceptDescriptor<float>(
            "PositionLimitX", "Position", "PositionLimitX", ConceptValueFamily.Floating,
            new FloatCodec(0f, 10f), new[] { "How far, in metres, leaning left or right can move the view." }, null);

        /// <summary>[Position] PositionLimitY.</summary>
        public static readonly ConceptDescriptor<float> PositionLimitY = new ConceptDescriptor<float>(
            "PositionLimitY", "Position", "PositionLimitY", ConceptValueFamily.Floating,
            new FloatCodec(0f, 10f), new[] { "How far, in metres, raising your head can move the view." }, null);

        /// <summary>[Position] PositionLimitYDown.</summary>
        public static readonly ConceptDescriptor<float> PositionLimitYDown = new ConceptDescriptor<float>(
            "PositionLimitYDown", "Position", "PositionLimitYDown", ConceptValueFamily.Floating,
            new FloatCodec(0f, 10f), new[] { "How far, in metres, lowering your head can move the view." }, null);

        /// <summary>[Position] PositionLimitZ.</summary>
        public static readonly ConceptDescriptor<float> PositionLimitZ = new ConceptDescriptor<float>(
            "PositionLimitZ", "Position", "PositionLimitZ", ConceptValueFamily.Floating,
            new FloatCodec(0f, 10f), new[] { "How far, in metres, leaning forward can move the view." }, null);

        /// <summary>[Position] PositionLimitZBack.</summary>
        public static readonly ConceptDescriptor<float> PositionLimitZBack = new ConceptDescriptor<float>(
            "PositionLimitZBack", "Position", "PositionLimitZBack", ConceptValueFamily.Floating,
            new FloatCodec(0f, 10f), new[] { "How far, in metres, leaning back can move the view." }, null);

        /// <summary>[Position] CollisionEnabled.</summary>
        public static readonly ConceptDescriptor<bool> CollisionEnabled = new ConceptDescriptor<bool>(
            "CollisionEnabled", "Position", "CollisionEnabled", ConceptValueFamily.Bool,
            new BoolCodec(), new[] { "true: leaning stops at walls instead of moving the view through them." }, null);

        /// <summary>[Position] CollisionMargin.</summary>
        public static readonly ConceptDescriptor<float> CollisionMargin = new ConceptDescriptor<float>(
            "CollisionMargin", "Position", "CollisionMargin", ConceptValueFamily.Floating,
            new FloatCodec(0f, float.MaxValue), new[] { "How far the view is held off a wall when you lean into it, in the game's own units." }, null);

        /// <summary>[Position] CollisionChannel.</summary>
        public static readonly ConceptDescriptor<int> CollisionChannel = new ConceptDescriptor<int>(
            "CollisionChannel", "Position", "CollisionChannel", ConceptValueFamily.Integer,
            new IntCodec(int.MinValue, int.MaxValue), new[] { "Which of the game's collision channels the wall check tests against." }, null);

        /// <summary>[Position] CollisionReleaseSmoothing.</summary>
        public static readonly ConceptDescriptor<float> CollisionReleaseSmoothing = new ConceptDescriptor<float>(
            "CollisionReleaseSmoothing", "Position", "CollisionReleaseSmoothing", ConceptValueFamily.Floating,
            new FloatCodec(0f, 1f), new[] { "How gently the view eases back out after a wall stopped a lean.", "0 is the quickest, 1 the slowest." }, null);

        /// <summary>[Position] TrackerPivotForward.</summary>
        public static readonly ConceptDescriptor<float> TrackerPivotForward = new ConceptDescriptor<float>(
            "TrackerPivotForward", "Position", "TrackerPivotForward", ConceptValueFamily.Floating,
            new FloatCodec(0f, 10f), new[] { "Metres from the pivot of your neck forward to the point the tracker follows.", "Used to remove the lean that turning your head adds. 0 here and in TrackerPivotUp turns it off." }, null);

        /// <summary>[Position] TrackerPivotUp.</summary>
        public static readonly ConceptDescriptor<float> TrackerPivotUp = new ConceptDescriptor<float>(
            "TrackerPivotUp", "Position", "TrackerPivotUp", ConceptValueFamily.Floating,
            new FloatCodec(0f, 10f), new[] { "Metres from the pivot of your neck up to the point the tracker follows." }, null);

        /// <summary>[Hotkeys] ToggleKey.</summary>
        public static readonly ConceptDescriptor<string> ToggleKey = new ConceptDescriptor<string>(
            "ToggleKey", "Hotkeys", "ToggleKey", ConceptValueFamily.Hotkey,
            new HotkeyCodec(), new[] { "Turns head tracking on and off." }, "End, Ctrl+Shift+Y");

        /// <summary>[Hotkeys] CycleTrackingModeKey.</summary>
        public static readonly ConceptDescriptor<string> CycleTrackingModeKey = new ConceptDescriptor<string>(
            "CycleTrackingModeKey", "Hotkeys", "CycleTrackingModeKey", ConceptValueFamily.Hotkey,
            new HotkeyCodec(), new[] { "Changes the tracking mode: rotation and position, rotation only, position only." }, "PageUp, Ctrl+Shift+G");

        /// <summary>[Hotkeys] YawModeKey.</summary>
        public static readonly ConceptDescriptor<string> YawModeKey = new ConceptDescriptor<string>(
            "YawModeKey", "Hotkeys", "YawModeKey", ConceptValueFamily.Hotkey,
            new HotkeyCodec(), new[] { "Switches yaw between the world's up axis and the camera's own (WorldSpaceYaw)." }, "PageDown, Ctrl+Shift+H");

        /// <summary>[Hotkeys] TrueFreeLookKey.</summary>
        public static readonly ConceptDescriptor<string> TrueFreeLookKey = new ConceptDescriptor<string>(
            "TrueFreeLookKey", "Hotkeys", "TrueFreeLookKey", ConceptValueFamily.Hotkey,
            new HotkeyCodec(), new[] { "Switches between keeping your eye on the sights and true free look (TrueFreeLook)." }, "Insert, Ctrl+Shift+U");

        /// <summary>[Light] LightFollowsHead.</summary>
        public static readonly ConceptDescriptor<bool> LightFollowsHead = new ConceptDescriptor<bool>(
            "LightFollowsHead", "Light", "LightFollowsHead", ConceptValueFamily.Bool,
            new BoolCodec(), new[] { "true: a light you carry points where you look instead of where you aim." }, null);

        /// <summary>[Light] LightMultiplier.</summary>
        public static readonly ConceptDescriptor<float> LightMultiplier = new ConceptDescriptor<float>(
            "LightMultiplier", "Light", "LightMultiplier", ConceptValueFamily.Floating,
            new FloatCodec(0f, 5f), new[] { "How far the light turns for each degree your head turns.", "1 matches the view, 0 keeps the light on your aim." }, null);

        /// <summary>In the schema's concepts order, which is the order a section's concept rows are written in.</summary>
        internal static readonly ConceptDescriptor[] All =
        {
            UdpPort,
            EnableOnStartup,
            LocalSmoothing,
            RemoteSmoothing,
            WorldSpaceYaw,
            AimDecoupling,
            RotationEnabled,
            DataFreshnessMs,
            PositionEnabled,
            PositionAllowed,
            TrueFreeLook,
            PositionLimitX,
            PositionLimitY,
            PositionLimitYDown,
            PositionLimitZ,
            PositionLimitZBack,
            CollisionEnabled,
            CollisionMargin,
            CollisionChannel,
            CollisionReleaseSmoothing,
            TrackerPivotForward,
            TrackerPivotUp,
            ToggleKey,
            CycleTrackingModeKey,
            YawModeKey,
            TrueFreeLookKey,
            LightFollowsHead,
            LightMultiplier,
        };

        /// <summary>The schema's sections, in the order a canonical file writes them.</summary>
        internal static readonly string[] Sections =
        {
            "Network",
            "General",
            "Sensitivity",
            "Inversion",
            "Smoothing",
            "Position",
            "Hotkeys",
            "Reticle",
            "Light",
        };

        /// <summary>
        /// The line a player is shown for a key of a concept the canonical format does not write,
        /// by the name <see cref="ConfigKeySchema.Resolve"/> returns for its key and every alias.
        /// </summary>
        internal static readonly Dictionary<string, string> NonCanonicalReasons = new Dictionary<string, string>
        {
            { "yawsensitivity", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own." },
            { "pitchsensitivity", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own." },
            { "rollsensitivity", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own." },
            { "invertyaw", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own." },
            { "invertpitch", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own." },
            { "invertroll", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own." },
            { "showreticle", "Whether a reticle is shown is not a setting." },
            { "reticlecolor", "The reticle colour is not a setting." },
            { "positionsensitivityx", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own." },
            { "positionsensitivityy", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own." },
            { "positionsensitivityz", "The mod applies the head pose as the tracker sends it, with no sensitivity of its own." },
            { "invertpositionx", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own." },
            { "invertpositiony", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own." },
            { "invertpositionz", "The mod applies the head pose as the tracker sends it, with no axis inversion of its own." },
            { "positiontogglekey", "CycleTrackingModeKey is the hotkey that switches positional tracking." },
            { "reticletogglekey", "The reticle has no toggle key." },
            { "recenterkey", "The mod keeps no centre of its own: centre the view in your tracker app." },
        };

        /// <summary>
        /// The line a player is shown for a spelling of a setting the canonical format does not
        /// write that is no concept (the schema's non_canonical_keys), by the spelling under
        /// <see cref="ConfigKeySchema.Normalize"/>. <see cref="ConfigKeySchema.Resolve"/> does not
        /// know these spellings, so the flat readers never read them.
        /// </summary>
        internal static readonly Dictionary<string, string> NonCanonicalKeyReasons = new Dictionary<string, string>
        {
            { "deadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own." },
            { "deadzonedeg", "The mod applies the head pose as the tracker sends it, with no deadzone of its own." },
            { "deadzoneyaw", "The mod applies the head pose as the tracker sends it, with no deadzone of its own." },
            { "deadzonepitch", "The mod applies the head pose as the tracker sends it, with no deadzone of its own." },
            { "deadzoneroll", "The mod applies the head pose as the tracker sends it, with no deadzone of its own." },
            { "yawdeadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own." },
            { "pitchdeadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own." },
            { "rolldeadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own." },
            { "enabledeadzone", "The mod applies the head pose as the tracker sends it, with no deadzone of its own." },
            { "responsecurve", "The mod applies the head pose as the tracker sends it, with no response curve of its own." },
            { "yawcurve", "The mod applies the head pose as the tracker sends it, with no response curve of its own." },
            { "pitchcurve", "The mod applies the head pose as the tracker sends it, with no response curve of its own." },
            { "rollcurve", "The mod applies the head pose as the tracker sends it, with no response curve of its own." },
        };
    }
}
